apiVersion: v1
kind: Pod
metadata:
  name: builder-pod
spec:
  containers:
  - name: builder
    image: roie710/builder-image:18
    command: ["sleep"]
    args: ["9999999"]
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "1"
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker

  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
